<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="53" started-at="2019-05-24T05:39:34Z" finished-at="2019-05-24T05:39:34Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="53" started-at="2019-05-24T05:39:34Z" finished-at="2019-05-24T05:39:34Z">
      <class name="com.vend.testcases.TC_01_Manager_Creation">
        <test-method status="FAIL" signature="create_User_Manager(java.util.Map)[pri:0, instance:com.vend.testcases.TC_01_Manager_Creation@57250572]" name="create_User_Manager" duration-ms="0" started-at="2019-05-24T11:09:34Z" data-provider="newManagerData" finished-at="2019-05-24T11:09:34Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void com.vend.testcases.TC_01_Manager_Creation.create_User_Manager(java.util.Map) requires a @DataProvider named : newManagerData in class com.backbase.utilLibrary.DataProviderRep_HashMap]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void com.vend.testcases.TC_01_Manager_Creation.create_User_Manager(java.util.Map) requires a @DataProvider named : newManagerData in class com.backbase.utilLibrary.DataProviderRep_HashMap
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:265)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:414)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_User_Manager -->
      </class> <!-- com.vend.testcases.TC_01_Manager_Creation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
